language: perl6
perl6:
  - latest

os:
  - linux
  - osx
  - windows

env:
  global:
    - export PATH="/opt/rakudo-pkg/bin:/opt/rakudo-pkg/share/perl6/site/bin:$PATH"
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/nxadm/rakudo-pkg-debs $(lsb_release -cs) main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?search=0x379CE192D401AB61&op=get'
    packages:
      - rakudo-pkg

before_install:
    # Display OS name
  - echo $TRAVIS_OS_NAME

  # Debian-based libsdl2 installation
  # Fix weird unmet dependency when installing libsdl2-dev
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update                                 ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libsdl2-dev                     ; fi

  # macOS rakudo-star and sdl2 installation
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew update                              ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew install rakudo-star sdl2 pkg-config ; fi


  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then 
                                
            choco install rakudostar wget 7zip;
            SET SDL2_ARCHIVE=SDL2-2.0.8-win32-x64.zip ;
            cd %TRAVIS_BUILD_DIR%
            wget https://libsdl.org/release/%SDL2_ARCHIVE% ;
            7z x %SDL2_ARCHIVE% ;
            refreshenv ; fi


install:
  - zef install . && zef test . --verbose
