language: shell
perl6:
  - latest

os:
  - linux
  - osx
  - windows

env:
  global:
    - export PATH="/opt/rakudo-pkg/bin:/c/rakudo/bin:/rakudo/bin:/opt/rakudo-pkg/share/perl6/site/bin:$PATH"
    - export FOO="zz"
    - export SDL2_ARCHIVE="SDL2-2.0.8-win32-x64.zip"
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/nxadm/rakudo-pkg-debs $(lsb_release -cs) main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?search=0x379CE192D401AB61&op=get'
    packages:
      - rakudo-pkg

before_install:
    # Display OS name
  - echo $TRAVIS_OS_NAME

  # Debian-based libsdl2 installation
  # Fix weird unmet dependency when installing libsdl2-dev
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update                                 ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libsdl2-dev                     ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then zef --version                                      ; fi

  # macOS rakudo-star and sdl2 installation
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew install rakudo-star sdl2 pkg-config ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then git clone https://github.com/ugexe/zef.git ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then cd zef ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then perl6 -I. bin/zef install . ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then zef --version ; fi

#  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then             dir c:\ ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then             ls -l /c/ ; fi
#  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then             tree / ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then             echo $SDL2_ARCHIVE ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then             cd "$TRAVIS_BUILD_DIR" ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then             choco install  wget 7zip ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then             wget https://libsdl.org/release/$SDL2_ARCHIVE ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then             7z x $SDL2_ARCHIVE ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then             choco install rakudostar ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then             which perl6 ; fi
#  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then             source ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then git clone https://github.com/ugexe/zef.git ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then cd zef ; fi
#  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then /rakudo/bin/perl6.bat  -I. bin/zef install . ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then perl6  -I. bin/zef install . ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then zef --version ; fi
  - if [ "$TRAVIS_OS_NAME" == "windows"   ]; then             refreshenv ; fi


install:
  - zef --version
  - zef info zef
  - zef install . && zef test . --verbose
