os: Visual Studio 2015

platform: x64

environment:
        matrix:
        #latest
        - test_moar: ''

install:
  # Install rakudostar for faster CI builds. No windows user will actually use
  # rakudobrew
  - choco install rakudostar wget
  # Change to build folder
  - cd %APPVEYOR_BUILD_FOLDER%
  # Download and unzip SDL2 Zip archive
  - SET SDL2_ARCHIVE=SDL2-2.0.8-win32-x64.zip
  - wget https://libsdl.org/release/%SDL2_ARCHIVE%
  - 7z x %SDL2_ARCHIVE%
  # Refresh environment variables so zef works
  - refreshenv
  - zef --version

build: off

test_script:
  # Test for fun :)
  - zef install . --verbose

shallow_clone: true
